import { useState } from 'react';
import { CheckCircle2, CircleDollarSign, GitBranch, ShieldCheck } from 'lucide-react';
import { Reveal, SectionHeading } from './Reveal';

const SNIPPETS: Record<string, { file: string; lines: { t: string; c?: string }[] }> = {
  docker: {
    file: 'Dockerfile',
    lines: [
      { t: '# generated by docker-architect', c: 'text-slate-500' },
      { t: 'FROM node:20-alpine AS build', c: 'text-navy-300' },
      { t: 'WORKDIR /app' },
      { t: 'COPY package*.json ./' },
      { t: 'RUN npm ci --omit=dev', c: 'text-copper-300' },
      { t: 'COPY . .' },
      { t: 'RUN npm run build', c: 'text-copper-300' },
      { t: 'FROM node:20-alpine', c: 'text-navy-300' },
      { t: 'USER node  # non-root enforced', c: 'text-emerald-400' },
      { t: 'EXPOSE 8080' },
      { t: 'CMD ["node", "dist/server.js"]' },
    ],
  },
  terraform: {
    file: 'main.tf',
    lines: [
      { t: '# generated by terraform-generator', c: 'text-slate-500' },
      { t: 'module "vpc" {', c: 'text-navy-300' },
      { t: '  source  = "terraform-aws-modules/vpc/aws"' },
      { t: '  cidr    = "10.0.0.0/16"' },
      { t: '}' },
      { t: 'module "eks" {', c: 'text-navy-300' },
      { t: '  cluster_name    = "infragenie-prod"' },
      { t: '  node_min_size   = 2', c: 'text-copper-300' },
      { t: '  node_max_size   = 8  # hpa-ready', c: 'text-emerald-400' },
      { t: '}' },
    ],
  },
  k8s: {
    file: 'deployment.yaml',
    lines: [
      { t: '# generated by k8s-synthesizer', c: 'text-slate-500' },
      { t: 'apiVersion: apps/v1', c: 'text-navy-300' },
      { t: 'kind: Deployment' },
      { t: 'metadata:' },
      { t: '  name: api-server' },
      { t: 'spec:' },
      { t: '  replicas: 3', c: 'text-copper-300' },
      { t: '  strategy: RollingUpdate' },
      { t: '  resources:  # right-sized by cost-optimizer', c: 'text-emerald-400' },
      { t: '    requests: { cpu: 250m, memory: 512Mi }' },
    ],
  },
  cicd: {
    file: 'deploy.yml',
    lines: [
      { t: '# generated by cicd-engine', c: 'text-slate-500' },
      { t: 'name: deploy', c: 'text-navy-300' },
      { t: 'on: { push: { branches: [main] } }' },
      { t: 'jobs:' },
      { t: '  test:     # stage 1', c: 'text-slate-400' },
      { t: '  build:    # stage 2 · docker buildx', c: 'text-slate-400' },
      { t: '  deploy:   # stage 3 · kubectl rollout', c: 'text-copper-300' },
      { t: '    needs: [test, build]' },
      { t: '    environment: production' },
    ],
  },
};

const TABS = [
  { id: 'docker', label: 'Docker' },
  { id: 'terraform', label: 'Terraform' },
  { id: 'k8s', label: 'Kubernetes' },
  { id: 'cicd', label: 'CI/CD' },
];

const AGENT_ROWS = [
  { name: 'stack-detector', status: 'done' },
  { name: 'docker-architect', status: 'done' },
  { name: 'k8s-synthesizer', status: 'done' },
  { name: 'security-hardener', status: '2 findings resolved' },
];

export default function ProductShowcase() {
  const [tab, setTab] = useState('docker');
  const snippet = SNIPPETS[tab];

  return (
    <section id="product" data-testid="product-section" className="relative py-24 lg:py-36">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-12">
        <SectionHeading
          chapter="CHAPTER 03"
          eyebrow="The Product"
          align="center"
          title={
            <>
              Your infrastructure{' '}
              <span className="bg-gradient-to-r from-copper-300 to-copper-500 bg-clip-text text-transparent">
                command center
              </span>
            </>
          }
          description="Every agent run, every generated artifact, every deployment — visible, reviewable and approvable in one place."
        />

        <Reveal delay={0.15} className="mt-16">
          <div className="relative mx-auto max-w-5xl">
            {/* Spotlight beam */}
            <div className="pointer-events-none absolute -top-24 left-1/2 h-64 w-[130%] -translate-x-1/2 bg-[radial-gradient(ellipse_50%_100%_at_50%_0%,rgba(201,105,42,0.22),transparent_70%)]" />

            <div className="relative rounded-3xl" data-testid="product-frame">
              <div className="beam-border rounded-3xl" aria-hidden="true" />
              <div className="relative m-[2px] overflow-hidden rounded-[22px] border border-white/10 bg-ink-900/90 shadow-[0_40px_120px_rgba(0,0,0,0.6)] backdrop-blur-xl">
                {/* Window chrome */}
                <div className="flex items-center gap-2 border-b border-white/[0.07] bg-white/[0.02] px-5 py-3.5">
                  <span className="h-3 w-3 rounded-full bg-rose-500/60" />
                  <span className="h-3 w-3 rounded-full bg-amber-400/60" />
                  <span className="h-3 w-3 rounded-full bg-emerald-400/60" />
                  <span className="ml-3 hidden rounded-md border border-white/10 bg-white/[0.04] px-3 py-1 font-mono text-[11px] text-slate-500 sm:block">
                    app.infragenie.io/deployments
                  </span>
                  <span className="ml-auto flex items-center gap-1.5 rounded-full border border-emerald-400/20 bg-emerald-400/10 px-2.5 py-1 font-mono text-[10px] text-emerald-300">
                    <span className="status-dot h-1.5 w-1.5 rounded-full bg-emerald-400" /> LIVE
                  </span>
                </div>

                <div className="grid lg:grid-cols-12">
                  {/* Agent rail */}
                  <div className="border-b border-white/[0.07] p-5 lg:col-span-4 lg:border-b-0 lg:border-r">
                    <p className="font-mono text-[10px] uppercase tracking-[0.22em] text-slate-500">
                      Agent run · acme/web-app
                    </p>
                    <div className="mt-4 space-y-2.5">
                      {AGENT_ROWS.map((a) => (
                        <div
                          key={a.name}
                          className="flex items-center justify-between rounded-lg border border-white/[0.06] bg-white/[0.03] px-3 py-2.5"
                        >
                          <span className="flex items-center gap-2 font-mono text-xs text-slate-300">
                            <GitBranch size={12} className="text-slate-500" />
                            {a.name}
                          </span>
                          <span className="flex items-center gap-1 text-[11px] text-emerald-400">
                            <CheckCircle2 size={12} />
                            {a.status}
                          </span>
                        </div>
                      ))}
                    </div>
                    <div className="mt-4 flex items-center justify-between rounded-lg border border-copper-500/25 bg-copper-500/[0.08] px-3 py-2.5">
                      <span className="flex items-center gap-2 text-xs text-slate-300">
                        <CircleDollarSign size={13} className="text-copper-400" />
                        Est. monthly cost
                      </span>
                      <span className="font-display text-sm font-bold text-copper-300">$214</span>
                    </div>
                    <div className="mt-2.5 flex items-center gap-2 rounded-lg border border-white/[0.06] bg-white/[0.03] px-3 py-2.5 text-[11px] text-slate-400">
                      <ShieldCheck size={13} className="text-emerald-400" />
                      Zero-trust policies attached
                    </div>
                  </div>

                  {/* Code preview */}
                  <div className="p-5 lg:col-span-8">
                    <div className="flex gap-1 rounded-xl border border-white/[0.07] bg-white/[0.02] p-1">
                      {TABS.map((t) => (
                        <button
                          key={t.id}
                          data-testid={`product-tab-${t.id}`}
                          onClick={() => setTab(t.id)}
                          className={`flex-1 rounded-lg px-3 py-2 text-xs font-semibold transition-all duration-300 ${
                            tab === t.id
                              ? 'bg-copper-500/15 text-copper-300 shadow-[inset_0_0_0_1px_rgba(201,105,42,0.35)]'
                              : 'text-slate-400 hover:text-slate-200'
                          }`}
                        >
                          {t.label}
                        </button>
                      ))}
                    </div>
                    <div className="mt-4 rounded-xl border border-white/[0.07] bg-ink-950/80">
                      <div className="flex items-center justify-between border-b border-white/[0.06] px-4 py-2.5">
                        <span className="font-mono text-[11px] text-slate-500">deployment/{snippet.file}</span>
                        <span className="rounded bg-emerald-400/10 px-2 py-0.5 font-mono text-[10px] text-emerald-400">
                          ✓ validated
                        </span>
                      </div>
                      <pre className="overflow-x-auto p-4 font-mono text-[11.5px] leading-[1.7]">
                        {snippet.lines.map((l, i) => (
                          <div key={`${tab}-${i}`} className="flex">
                            <span className="w-7 shrink-0 select-none text-right text-slate-700">{i + 1}</span>
                            <span className={`pl-4 ${l.c ?? 'text-slate-300'}`}>{l.t}</span>
                          </div>
                        ))}
                      </pre>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </Reveal>
      </div>
    </section>
  );
}
